### ISSUE TITLE
Issues with Batch Prompt Schedule

### ISSUE THREAD

**Issue by ptmarks** [FizzleDorf/ComfyUI_FizzNodes#60] opened 2024-01-25 08:50 UTC
I'm getting an error with Batch Prompt Schedule: RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 154 but got size 77 for tensor number 12 in the list. I'm not sure if it's because there is a limit for the number of characters in the prompt or something else. I can use my prompts up to a point, but if I add another prompt schedule line I get the error above. 

Probably unrelated, I'm also getting this warning: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'photo realistic girl high quality, detailed, high resolution, 4k' has dtype incompatible with float64, please explicitly cast to a compatible dtype first. Do I need to change the wording?

**Comment by revolutioncom123** [comment] 2024-01-25 09:13
i am getting the same problem too and sometimes gettings:

Error occurred when executing BatchPromptSchedule:

Expression 0 1.00
1 0.97
2 0.94
3 0.91
4 0.87
5 0.84
6 0.81
7 0.78
dtype: float64 has forbidden control characters.

**Comment by revolutioncom123** [comment] 2024-01-25 09:51
i needed to roll back to cd6cadd71c0865725bcc6ba63a66ecb4460a09b8 to stop having this problem.

**Comment by Emersonksc** [comment] 2024-01-25 14:54
@revolutioncom123 To clarify, when writing expressions, use single quotation marks (') instead of double backticks (`) as they have been causing issues. However, there seems to be some inconsistency as some sources, such as the wiki, previously recommended using double backticks. It is possible that the best course of action is to leave this decision to the author.

> i am getting the same problem too and sometimes gettings:
> 
> Error occurred when executing BatchPromptSchedule:
> 
> Expression 0 1.00 1 0.97 2 0.94 3 0.91 4 0.87 5 0.84 6 0.81 7 0.78 dtype: float64 has forbidden control characters.

**Comment by revolutioncom123** [comment] 2024-01-25 16:10
i already check everything but this message is some type of bug. i tried to replicate everything of the wiki and tried a lot of differents ways to write the setence but still giving me the bug.I think i going to wait for the answer this bug always occour when i using batch BatchPromptSchedule with more the two time lapses and using  pw_a and pw_b in value prompt schedule.

**Comment by Emersonksc** [comment] 2024-01-26 07:32
@FizzleDorf, actually, this is an error when I work with animatediff, so plz upload some workflows related to batchPromptSchedule and batchPromptValue nodes, just like revolutioncom123 said, this error fixes when you reset the repo to cd6cadd

> i needed to roll back to [cd6cadd](https://github.com/FizzleDorf/ComfyUI_FizzNodes/commit/cd6cadd71c0865725bcc6ba63a66ecb4460a09b8) to stop having this problem.

**Comment by FizzleDorf** [comment] 2024-01-26 07:38
can you provide the workflow you are having issues with and I can work with that. I'll make a new example once the issue is resolved.

**Comment by FizzleDorf** [comment] 2024-01-26 12:23
> i am getting the same problem too and sometimes gettings:
> 
> Error occurred when executing BatchPromptSchedule:
> 
> Expression 0 1.00 1 0.97 2 0.94 3 0.91 4 0.87 5 0.84 6 0.81 7 0.78 dtype: float64 has forbidden control characters.

This issue has been fixed with this commit d32d37c

I'll be looking into the datatype issue after I solve the tensor size error

**Comment by FizzleDorf** [comment] 2024-01-26 15:59
The previously mentioned commit apparently fixed the padding issue! I had some people test for me so it's safe to pull. I'll close this issue and work on the dtype warning when able.

**Closed by FizzleDorf** 2024-01-26 15:59 UTC
