### ISSUE TITLE
FizzNodes not working since last ComfyUI update.

### ISSUE THREAD

**Issue by lord-lethris** [FizzleDorf/ComfyUI_FizzNodes#6] opened 2023-09-08 16:23 UTC
Since updating today - I get the following error with ComfyUI_FizzNodes

```
  File "D:\apps\SD-WebUI\ComfyUI\custom_nodes\ComfyUI_FizzNodes\__init__.py", line 57, in <module>
    from .ScheduledNodes import ValueSchedule, PromptSchedule, PromptScheduleNodeFlow, PromptScheduleNodeFlowEnd, PromptScheduleEncodeSDXL #, PromptScheduleGLIGEN
  File "D:\apps\SD-WebUI\ComfyUI\custom_nodes\ComfyUI_FizzNodes\ScheduledNodes.py", line 11, in <module>
    from .ScheduleFuncs import check_is_number, interpolate_prompts, interpolate_prompts_SDXL, PoolAnimConditioning, PoolAnimConditioningGligen
ImportError: cannot import name 'PoolAnimConditioningGligen' from 'ComfyUI_FizzNodes.ScheduleFuncs' (D:\apps\SD-WebUI\ComfyUI\custom_nodes\ComfyUI_FizzNodes\ScheduleFuncs.py)

Cannot import D:\apps\SD-WebUI\ComfyUI\custom_nodes\ComfyUI_FizzNodes module for custom nodes: cannot import name 'PoolAnimConditioningGligen' from 'ComfyUI_FizzNodes.ScheduleFuncs' (D:\apps\SD-WebUI\ComfyUI\custom_nodes\ComfyUI_FizzNodes\ScheduleFuncs.py)
```

**Comment by FizzleDorf** [comment] 2023-09-09 13:05
thanks for letting me know, I must have uncommented some code while I was working. The issue is fixed in this commit 53290fd

**Closed by FizzleDorf** 2023-09-09 13:05 UTC
